name: Format checker
on: [pull_request]

jobs:
    review:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'
            - run: npm ci && npm run format && npm run lint && npm run lint:style
